server:
  port: 9090
spring:
  application:
    name: biletimcepte-gateway
  cloud:
    gateway:
      routes:
        - id: biletimcepte-service
          uri: http://localhost:8090
          predicates:
            - Path=/users/**,/voyages/**,/tickets/**,/bookings/**
        - id: biletimcepte-payment-service
          uri: http://localhost:8095
          predicates:
            - Path=/payments/**

  eureka:
    client:
      enabled: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
        instance:
          prefer-ip-address: true